const productos = [
  {
    id: 1,
    titulo: "Promo 1",
    descripcion: "Para 2 personas, lomos, papas y bebida",
    precio: 25000,
    img: "lomop1.jpg",
  },
  {
    id: 2,
    titulo: "Promo 2",
    descripcion: "Para 4 personas, lomos papas y bebida",
    precio: 48000,
    img: "lomop2.jpg",
  },
  {
    id: 3,
    titulo: "Promo 3",
    descripcion: "Para 6 personas, lomos papas y bebida",
    precio: 70000,
    img: "lomop3.jpg",
  },
  {
    id: 4,
    titulo: "Promo 4",
    descripcion: "Para 2 personas, hamburguesas papas y bebida",
    precio: 15000,
    img: "hambp1.jpg",
  },
  {
    id: 5,
    titulo: "Promo 5",
    descripcion: "Para 4 personas, hamburguesas papas y bebida",
    precio: 28000,
    img: "hambp2.jpg",
  },
  {
    id: 6,
    titulo: "Promo 6",
    descripcion: "Para 6 personas, hamburguesas papas y bebida",
    precio: 40000,
    img: "hambp3.jpg",
  },
  {
    id: 7,
    titulo: "Promo 7",
    descripcion: "Para 2 personas, pizzas papas y bebida",
    precio: 12000,
    img: "pizzap1.jpg",
  },
  {
    id: 8,
    titulo: "Promo 8",
    descripcion: "Para 4 personas, pizzas papas y bebida",
    precio: 21000,
    img: "pizzap2.jpg",
  },
  {
    id: 9,
    titulo: "Promo 9",
    descripcion: "Para 6 personas, pizzas papas y bebida",
    precio: 30000,
    img: "pizzap3.jpg",
  },
];
